___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:
Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:
Розв'яжіть систему рівнянь:

In [9]:
import numpy as np  

Вивести версію та конфігурацію бібліотеки:

In [10]:
print("NumPy Version : ",np.__version__)
print(np.show_config())

NumPy Version :  1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/tlehka/AppData/Local/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/tlehka/AppData/Local/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/tlehka/AppData/Local/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/tlehka/AppData/Local/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/tlehka/AppData/Local/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/tlehka/AppData/Local/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/tlehka/AppData/Local/anaconda3\\Li

Створити вектор з 10 елементів, заповнений одиницями:

In [11]:
array = np.ones(10)

In [12]:
array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [13]:
array = np.arange(1, 11)

In [14]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [15]:
number_for_full = 0
np.full((5, 5), number_for_full)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [55]:
array = np.random.randint(0,5,20)

In [56]:
array

array([0, 1, 2, 2, 2, 4, 1, 2, 2, 4, 0, 0, 2, 4, 3, 0, 0, 3, 4, 0])

In [58]:
np.nonzero(array)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 12, 13, 14, 17, 18],
       dtype=int64),)

Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [18]:
array.mean()

43.75

In [19]:
np.median(array)

35.5

In [20]:
np.std(array)

28.965280941154358

Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [21]:
matrix = np.random.randint(1, 10, (4,2))

In [22]:
matrix2 = np.random.randint(1, 10, (2,2))

In [23]:
matrix

array([[6, 3],
       [1, 8],
       [7, 4],
       [4, 5]])

In [24]:
matrix2

array([[3, 4],
       [7, 7]])

In [25]:
#Перемножити
matrixf = np.dot(matrix, matrix2)

In [26]:
matrixf

array([[39, 45],
       [59, 60],
       [49, 56],
       [47, 51]])

Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [27]:
vector=matrixf.flatten()

In [28]:
vector

array([39, 45, 59, 60, 49, 56, 47, 51])

In [29]:
vector.min()

39

In [30]:
vector.max()

60

In [31]:
#Максимальне значення замінити на 0
vector[np.where(vector==np.max(vector))] = 0

In [32]:
vector

array([39, 45, 59,  0, 49, 56, 47, 51])

Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [33]:
matrixf

array([[39, 45],
       [59, 60],
       [49, 56],
       [47, 51]])

In [53]:
#перший рядок матриці
matrixf[0]

array([39, 45])

In [54]:
np.corrcoef(matrixf[0],matrixf)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
import pandas as pd
import numpy as np

df = pd.DataFrame(matrixf)
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm')

Дано матрицю. Знайти ранг матриці:

In [36]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

In [37]:
#Ранг матриці — це максимальна кількість лінійно незалежних стовпців цієї матриці.
r = np.linalg.matrix_rank(a)

In [38]:
r

3

Знайти визначник матриці:

In [39]:
#Визна́чник або детерміна́нт — це функція від квадратної матриці, яка набуває скалярних значень. 
#Він характеризує багато властивостей матриці та лінійного відображення, визначеного цією матрицею.
det = np.linalg.det(a)

In [40]:
det

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [41]:
w, v = np.linalg.eig(a)

In [42]:
#власні числа
w

array([14.13520334+0.j        , -4.56760167+3.20389947j,
       -4.56760167-3.20389947j])

In [43]:
#власні вектори
v

array([[ 0.43131913+0.j        , -0.31386258-0.47450898j,
        -0.31386258+0.47450898j],
       [ 0.41502436+0.j        , -0.07049527+0.4090732j ,
        -0.07049527-0.4090732j ],
       [ 0.8010734 +0.j        ,  0.7099444 +0.j        ,
         0.7099444 -0.j        ]])

Знайдіть число, що найчастіше зустрічається в масиві:

In [44]:
a = np.random.randint(0,10,50)

In [45]:
a

array([9, 6, 5, 9, 1, 3, 1, 8, 0, 1, 2, 1, 4, 6, 6, 3, 9, 8, 9, 7, 8, 5,
       1, 0, 3, 1, 1, 7, 9, 2, 4, 4, 8, 8, 7, 8, 8, 0, 9, 9, 9, 7, 4, 3,
       6, 5, 3, 1, 7, 4])

In [46]:
#тільки додаткові значення
counts = np.bincount(a)
print(np.argmax(counts))

1


In [47]:
from collections import Counter
b = Counter(a)
print(b.most_common(1))

[(9, 8)]


In [48]:
import numpy as np
# Program to find most frequent
def most_frequent(a):
    unique, counts = np.unique(a, return_counts=True)
    index = np.argmax(counts)
    return unique[index]

In [49]:
print(most_frequent(a))

1


Виведіть лише парні числа, що діляться на 5:

In [50]:
a = np.random.randint(0,10,50)

In [51]:
a

array([9, 8, 6, 9, 3, 4, 7, 4, 2, 6, 1, 0, 7, 0, 2, 1, 3, 4, 4, 0, 1, 6,
       6, 5, 1, 6, 9, 6, 4, 1, 4, 6, 5, 6, 0, 8, 4, 9, 2, 4, 7, 6, 3, 6,
       5, 9, 3, 8, 5, 5])

In [52]:
for num in a:
 
    # checking condition
    if (num % 2 == 0 and num % 5==0):
        print(num, end=" ")

0 0 0 0 

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [68]:
start=np.matrix([[2, 5], [1, -10]])
finish=np.matrix([[1], [3]])

In [65]:
start

matrix([[  2,   5],
        [  1, -10]])

In [66]:
finish

matrix([[1],
        [3]])

In [69]:
np.linalg.solve(start,finish)

matrix([[ 1. ],
        [-0.2]])